apiVersion: apps/v1
kind: Deployment
metadata:
  name: suiyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suiyi
  template:
    metadata:
      labels:
        app: suiyi
    spec:
      containers:
      - image: okteto.dev/suiyi:latest
        name: suiyi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c08442bf-8490-4f58-b956-54f5b538110f"
        - name: Vless_Path
          value: "/l555"
        - name: Vmess_UUID
          value: "c08442bf-8490-4f58-b956-54f5b538110f"
        - name: Vmess_Path
          value: "/m555"
        - name: Share_Path
          value: "/v2link"
